### ISSUE TITLE
its/libc-header-start.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [CyberShadow/hax11#5]
I cannot seem to build the library... Here is the complete error:

```c
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
```
Specifications:
X86_64 Architecture
Ubuntu 20.04 OS

Command to download:
```bash
git clone https://github.com/CyberShadow/hax11
```

**Comment by CyberShadow** [comment]
The error is in your system's include files. It looks like there is a problem with your system or distribution.

Perhaps you are missing a package.

**Comment by ghost** [comment]
How may I download the necessary library?

**Comment by CyberShadow** [comment]
Sorry, I don't know. I don't use Ubuntu.

**Comment by ghost** [comment]
What would you do on *your* operating system?

**Comment by CyberShadow** [comment]
If I got that error on Arch Linux, I would check which package owns the missing file, and try installing it.

If that didn't work, I would probably ask on #archlinux on IRC.

**Comment by ghost** [comment]
Okay... How do I check the package and install it?

**Comment by CyberShadow** [comment]
I think this should help: https://askubuntu.com/a/1912/111511

**Comment by CyberShadow** [comment]
This seems related to the error you are seeing: https://askubuntu.com/questions/91909/trouble-compiling-a-32-bit-binary-on-a-64-bit-machine

**Comment by ghost** [comment]
Works!
