### ISSUE TITLE
Can't install hax11

### ISSUE THREAD

**Issue by ShinyZero0** [CyberShadow/hax11#7]
I'm new to linux, but i heard hax11 fixes some mouse problems with War Thunder. 
Firstly, i used `git clone`. Then it said i need some x,org libs to `make`, so i installed everything hax11 asked for (i found analogues for Fedora). 
Now there's no `home/.config/hax11` directory and when i try to launch a game it says
 `ERROR: ld.so: object '/home/shinyzero/hax11/$LIB/hax11.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
`
Also i tried to reboot but it didn't help

**Comment by CyberShadow** [comment]
> Now there's no `home/.config/hax11` directory

It will be created the first time a program is started with hax11 loaded.

> and when i try to launch a game

What commands exactly are you running? (To install hax11 and to start the game)

**Comment by ShinyZero0** [comment]
`cd hax11`
`export LD_PRELOAD='pwd'/\$LIB/hax11.so`
`steam steam://rungameid/236390`

replaced ` to ' in 'pwd' to make it look as it should

**Comment by CyberShadow** [comment]
> `export LD_PRELOAD='pwd'/\$LIB/hax11.so`

There is no way this would work. The single quotes need to be backticks for one.

> `steam steam://rungameid/236390`

You have to make sure Steam is not running if you want to do it that way.

You can check if hax11 is loaded in a process with `htop`, find the process and press <kbd>e</kbd>, then check if there's a `LD_PRELOAD` line.

**Comment by ShinyZero0** [comment]
> > `export LD_PRELOAD='pwd'/\$LIB/hax11.so`
> 
There is no way this would work. The single quotes need to be backticks for one.

i know, i replaced them cause they are hiding

**Comment by CyberShadow** [comment]
Got it. You can use three backticks to start a code block, you can put single backticks there.

I suggest exiting Steam, running the `export` command, then running `steam` from the same terminal, that should work.

War Thunder has a native Linux port?

**Comment by ShinyZero0** [comment]
Yes

**Comment by ShinyZero0** [comment]
> > > `export LD_PRELOAD='pwd'/\$LIB/hax11.so`
> 
> There is no way this would work. The single quotes need to be backticks for one.
 I know, i replaced them cause they are hiding

**Comment by ShinyZero0** [comment]
System said `htop` is wrong and `top` is the right command. I found the game (aces) process but when i press E it looks like the sort type is changing

**Comment by CyberShadow** [comment]
> System said `htop` is wrong and `top` is the right command

No, it's `htop` (it's auto-correcting using the knowledge of only the commands that you already have). Install `htop`, it's a great tool you'll probably want to have anyway.

**Comment by ShinyZero0** [comment]
What should i find there? Or how to copy text from `htop`? `LD_PRELOAD=/home/shinyzero/hax11/$LIB/hax11.so`

**Comment by CyberShadow** [comment]
> Or how to copy text from `htop`?

In most terminal emulators you can hold `Shift` to copy text from mouse-enabled terminal programs.



> `LD_PRELOAD=/home/shinyzero/hax11/$LIB/hax11.so`

Looks good, you should have a ~/.config/hax11 directory where you can add configuration.

**Comment by ShinyZero0** [comment]
yes, there is

**Comment by CyberShadow** [comment]
Great, problem solved?

**Comment by ShinyZero0** [comment]
Profiles will be enabled automatically or i should add something to launch parameters in Steam?

**Comment by CyberShadow** [comment]
Automatically, just make sure `Enable=1` is among the settings.

**Comment by ShinyZero0** [comment]
Got it, thank you very much
