### ISSUE TITLE
Bezel correction?

### ISSUE THREAD

**Issue by DocMAX** [CyberShadow/hax11#9]
Any chance to support some kind of bezel correction?

**Comment by CyberShadow** [comment]
I haven't encountered this problem, but this seems like something that needs to be done in the real X server. Couldn't you configure your monitors to have a gap between them with xrandr?

**Comment by CyberShadow** [comment]
You can then group the three physical monitors into a single RandR monitor object (`xrandr --setmonitor`). If the game doesn't support XRandR monitors (or you don't want to put everything in one RandR monitor), you could use hax11 to make it think the entire desktop is one monitor. Xinerama is also an older option but it's an "all-or-nothing" proposition.

**Comment by CyberShadow** [comment]
I hope this is answered.
